[server]
runOnSave = false
port = 8505
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "light"